export const siteConfig = {
  name: "Coco",
  url: "https://coco.griffen.codes",
  ogImage: "https://coco.griffen.codes/og-image.png",
  description:
    "A suite of AI-powered Git tools — smart commits, automated changelogs, code reviews, commit splitting, and recaps — exposed to developers through a keyboard-driven terminal workstation, a versioned agent CLI, and four local read-only MCP tools. PR/MR and issue triage works across GitHub, GitHub Enterprise, GitLab, and Bitbucket Cloud. Supports OpenAI, Anthropic, Gemini, Mistral, Azure OpenAI, AWS Bedrock, and Ollama for local/private operation.",
  keywords: [
    "git",
    "cli tool",
    "AI git commits",
    "automated changelogs",
    "code review",
    "commit splitting",
    "terminal git workstation",
    "developer tools",
    "AI assistant",
    "Model Context Protocol",
    "MCP server for Git",
    "coding agent CLI",
    "AI agent tools",
    "structured Git automation",
    "conventional commits",
    "git automation",
    "terminal tools",
    "git tui",
    "coco ui",
    "commit messages",
    "changelog generator",
    "github",
    "github enterprise",
    "gitlab",
    "multi-forge",
    "pull requests",
    "merge requests",
    "ollama",
    "openai",
    "anthropic",
    "git-coco",
    "AI git for GitLab",
    "GitLab AI commit",
    "GitLab merge request AI",
    "AI code review GitLab",
    "opencommit alternative",
    "aicommits alternative",
    "private AI code review",
    "local AI commits",
    "ollama git commit",
  ],
  links: {
    docs: "/docs",
    workstation: "/workstation",
    changelog: "/changelog",
    github: "https://github.com/gfargo/coco",
    githubProfile: "https://github.com/gfargo",
    discord: "https://discord.gg/KGu9nE9Ejx",
    npm: "https://www.npmjs.com/package/git-coco",
    discussions: "https://github.com/gfargo/coco/discussions",
    issues: "https://github.com/gfargo/coco/issues/new",
    wiki: "https://github.com/gfargo/coco/wiki",
    agentMcpWiki: "https://github.com/gfargo/coco/wiki/Agent-CLI-and-MCP",
    ollamaWiki: "https://github.com/gfargo/coco/wiki/Using-Ollama",
    commitPrompt:
      "https://github.com/gfargo/coco/blob/main/src/lib/langchain/prompts/commitDefault.ts#L3-L15",
  },
  author: {
    name: "Griffen Fargo",
    url: "https://github.com/gfargo",
    twitter: "@gfargo",
  },
}
